
 # Publish all joint states ----------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Position Controllers--------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid:  {p: 800.0, i: 0.01, d: 0.1}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: {p: 1000.0, i: 0.01, d: 0.1}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint3
    pid: {p: 800.0, i: 0.01, d: 0.1}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint4
    pid: {p: 800.0, i: 0.01, d: 0.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint5
    pid: {p: 800.0, i: 0.01, d: 0.1}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint6
    pid: {p: 800.0, i: 0.01, d: 0.1}

  gripperJoint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Claw
    pid: {p: 200.0, i: 0.01, d: 0.1}

 